name: mertcanoncul.com
type: docker
port: 3000
build:
  dockerfile: Dockerfile
  context: .
environment:
  - NODE_ENV=production
  - PORT=3000
  - NEXT_TELEMETRY_DISABLED=1
deploy:
  replicas: 1
  resources:
    memory: 1Gi
    cpu: 1
healthcheck:
  path: /api/health
  interval: 30s
  timeout: 3s
  retries: 3
  start_period: 5s
auto_deploy: true
